
package cn.itheima.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.itheima.com/")
@XmlSeeAlso({

})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SqlHello")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SqlHello", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SqlHello")
    @ResponseWrapper(localName = "SqlHelloResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SqlHelloResponse")
    public String sqlHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
