
package com.itheima.ax.service;

import com.itheima.ax.pojo.Customer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crm.itheima.com/")
@XmlSeeAlso({
   // ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateByCustomerIds", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpdateByCustomerIds")
    @ResponseWrapper(localName = "updateByCustomerIdsResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpdateByCustomerIdsResponse")
    public void updateByCustomerIds(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<String> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "emptyByDecidedzone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.EmptyByDecidedzone")
    @ResponseWrapper(localName = "emptyByDecidedzoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.EmptyByDecidedzoneResponse")
    public void emptyByDecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateByCustomerId", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpdateByCustomerId")
    @ResponseWrapper(localName = "updateByCustomerIdResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.UpdateByCustomerIdResponse")
    public void updateByCustomerId(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListNoAssociationDecidedzone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindListNoAssociationDecidedzone")
    @ResponseWrapper(localName = "findListNoAssociationDecidedzoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindListNoAssociationDecidedzoneResponse")
    public List<Customer> findListNoAssociationDecidedzone();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListAssociationDecidedzone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindListAssociationDecidedzone")
    @ResponseWrapper(localName = "findListAssociationDecidedzoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindListAssociationDecidedzoneResponse")
    public List<Customer> findListAssociationDecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itheima.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.crm.itheima.com/", className = "com.itheima.crm.service.FindDecidedzoneIdByAddressResponse")
    public String findDecidedzoneIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
